ALTER TABLE trades
ADD COLUMN name VARCHAR(255),
ADD COLUMN symbol VARCHAR(20),
ADD COLUMN side VARCHAR(10),
ADD COLUMN status VARCHAR(20),
ADD COLUMN filled INTEGER,
ADD COLUMN total_qty INTEGER,
ADD COLUMN price DECIMAL(10,2),
ADD COLUMN avg_price DECIMAL(10,2),
ADD COLUMN time_in_force VARCHAR(20),
ADD COLUMN placed_time TIMESTAMP,
ADD COLUMN filled_time TIMESTAMP;